include: package:lints/recommended.yaml

linter:
  # Note: Ensure rules are replicated where applicable in `analysis_options.flutter.yaml`
  rules:
    - always_declare_return_types
    - always_put_required_named_parameters_first
    - avoid_void_async
    - await_only_futures
    - curly_braces_in_flow_control_structures
    - omit_local_variable_types
    - prefer_interpolation_to_compose_strings
    - prefer_relative_imports
    - prefer_single_quotes
    - require_trailing_commas
    - unawaited_futures
    - unnecessary_final

analyzer:
  exclude:
    - lib/**.reflectable.dart
    - test/**.reflectable.dart
    - example/*.reflectable.dart
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
