name: runtime_structured_cli_args
description: A smart command line argument parser for Dart that provides
  argument validation, static type checking, command execution, beautiful
  help generation and more.
version: 0.0.1
homepage: https://github.com/open-runtime/structured_args

environment:
  sdk: '>=2.19.2 <3.3.9'

dev_dependencies:
  lints: ^2.0.1
  test: ^1.23.1
  build_runner: ^2.3.3
  build_test: ^2.1.6
  test_core: ^0.4.24

dependencies:
  path: ^1.8.3
  reflectable: ^4.0.5
  collection: ^1.17.1
  recase: ^4.1.0
  meta: ^1.9.0

